version: '2'
services:
  lucaspedrosoapp-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/lucasPedrosoApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lucasPedrosoApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
